name: Checks

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags-ignore:
      - '**'

jobs:
  php-syntax:
    name: PHP ${{ matrix.php-version }} Syntax
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version:
          - '7.1'
          - '8.4'
    steps:
      -
        name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: opcache
          coverage: none
          tools: none
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      -
        name: Check syntax
        uses: mlocati/check-php-syntax@v1
        with:
          fail-on-warnings: true

  php-cs:
    name: PHP Coding Style
    runs-on: ubuntu-latest
    steps:
      -
        name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: 'php-cs-fixer:v3'
          coverage: none
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      -
        name: Check coding style
        run: php-cs-fixer fix --dry-run --using-cache=no --diff --show-progress=none --verbose --no-interaction --ansi

  phpunit:
    name: PHPUnit PHP ${{ matrix.php-version }} on ${{ matrix.operating-system }}
    needs:
      - php-cs
      - php-syntax
    strategy:
      matrix:
        operating-system:
          - ubuntu-latest
        php-version:
          - '7.1'
          - '7.2'
          - '7.3'
          - '7.4'
          - '8.0'
          - '8.1'
          - '8.2'
          - '8.3'
          - '8.4'
        include:
          - php-version: '8.4'
            operating-system: ubuntu-latest
            code-coverage: xdebug
          - php-version: '7.1'
            operating-system: macos-latest
          - php-version: '7.1'
            operating-system: windows-latest
          - php-version: '8.4'
            operating-system: macos-latest
          - php-version: '8.4'
            operating-system: windows-latest
    runs-on: ${{ matrix.operating-system }}
    steps:
      -
        name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: 'composer:v2'
          coverage: ${{ matrix.code-coverage }}
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      -
        name: Install dependencies
        run: composer update --no-progress --optimize-autoloader --ansi --no-interaction
      -
        name: Perform tests
        if: "! matrix.code-coverage"
        run: composer run-script test -- --verbose
      -
        name: Perform tests (with code coverage)
        if: matrix.code-coverage
        run: composer run-script test -- --verbose --coverage-clover code-coverage.xml
      -
        name: Upload code coverage
        if: matrix.code-coverage
        uses: codecov/codecov-action@v5
        with:
          files: code-coverage.xml
          flags: unittests
          fail_ci_if_error: true
